"""bill documents and the document link on bills

Revision ID: 1baee1682c46
Revises: 4c3dd9fa0449
Create Date: 2026-08-13 23:43:28.461984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# uploaded_by points at user.id, which fastapi-users declares with its own GUID
# type. Autogenerate emits the type without emitting this import.
import fastapi_users_db_sqlalchemy.generics


revision: str = '1baee1682c46'
down_revision: Union[str, None] = '4c3dd9fa0449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('place_id', sa.Uuid(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.String(length=100), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('uploaded_by', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('place_id', 'sha256', name='uq_bill_documents_place_sha')
    )
    op.create_index('ix_bill_documents_place_id', 'bill_documents', ['place_id'], unique=False)
    op.create_index('ix_bill_documents_uploaded_by_created', 'bill_documents', ['uploaded_by', 'created_at'], unique=False)
    op.add_column('bills', sa.Column('document_id', sa.Uuid(), nullable=True))
    # Named, not autogenerate's None: downgrade() cannot drop a constraint whose
    # name PostgreSQL chose for us.
    op.create_foreign_key('fk_bills_document_id', 'bills', 'bill_documents', ['document_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_bills_document_id', 'bills', type_='foreignkey')
    op.drop_column('bills', 'document_id')
    op.drop_index('ix_bill_documents_uploaded_by_created', table_name='bill_documents')
    op.drop_index('ix_bill_documents_place_id', table_name='bill_documents')
    op.drop_table('bill_documents')
    # ### end Alembic commands ###
